In [1]:
import pandas

In [2]:
df = pandas.read_csv("athlete_events.csv")

In [3]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [4]:
df[df["Height"]>=200][["Name", "Height", "Age"]]

                                  Name  Height   Age
299                     Hossam Abdalla   203.0  28.0
443                 Mamdouh Abdelrehim   207.0  26.0
609         Julius Shareef Abdur-Rahim   202.0  23.0
820           Abdelhalim Muhammad Abou   210.0  27.0
833            Essameldin Abou El-Nein   205.0  29.0
...                                ...     ...   ...
271014  Ronald Ferdinand "Ron" Zwerver   200.0  21.0
271015  Ronald Ferdinand "Ron" Zwerver   200.0  25.0
271016  Ronald Ferdinand "Ron" Zwerver   200.0  29.0
271026                  Philip Zwiener   202.0  23.0
271091              ukasz Tomasz ygado   200.0  32.0

[2600 rows x 3 columns]

In [5]:
df[df["Name"].str.contains("keith", case=False)][["Name", "Height", "Age"]]

                                 Name  Height   Age
1477                      Keith Adams   167.0  22.0
5013    Ian Graeme Keith "Mick" Allen   190.0  18.0
5014    Ian Graeme Keith "Mick" Allen   190.0  22.0
5015    Ian Graeme Keith "Mick" Allen   190.0  26.0
7867                      Keith Angus   170.0  33.0
...                               ...     ...   ...
259762                Keith Whitehead   179.0  28.0
259817             Ryan Keith Whiting   191.0  25.0
260196                  Keith Wiegard   185.0  22.0
261509                   Keith Wilson   177.0  22.0
262808           Keith Eugene Woodall     NaN  29.0

[239 rows x 3 columns]

In [6]:
df.tail(9)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
271107,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972 Summer,1972,Summer,Munich,Football,Football Men's Football,NaN
271108,135567,Aleksandr Viktorovich Zyuzin,M,24.0,183.0,72.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Rowing,Rowing Men's Lightweight Coxless Fours,NaN
271109,135567,Aleksandr Viktorovich Zyuzin,M,28.0,183.0,72.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Rowing,Rowing Men's Lightweight Coxless Fours,NaN
271110,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016 Summer,2016,Summer,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [7]:
df["Height Category"] = df["Height"].apply(lambda x : 'short' if x < 165 else 'medium' if x < 180 else 'tall' )

In [8]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,Height Category
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,tall
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,medium
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,tall
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,tall
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,tall

In [9]:
df = df.drop(columns=["Height Category"]) # drop the column we just created if we don't use the word columns, it will drop the row with that name instead of the column

In [10]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [11]:
df.rename(columns={"Sex":"Gender"},inplace = True) # rename the column

In [12]:
df.head()

,ID,Name,Gender,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [13]:
df["first_name"] = df["Name"].str.split(' ').str[0]

In [14]:
df.head()

,ID,Name,Gender,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,first_name
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,A
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,A
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Gunnar
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Edgar
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Christine

In [15]:
df["Year"] = pandas.to_datetime(df["Year"], format="%d-%m-%Y") # convert the year column to datetime format   
df.head()

ValueError: time data "1992" doesn't match format "%d-%m-%Y". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
stud = pandas.DataFrame({'name': ['Alice', 'Bob', 'Charlie'], 'id': [1,2,3]})
stud_det = pandas.DataFrame({'id': [2,3,4], 'age': [20, 21, 22]})
pandas.merge(stud, stud_det, on = 'id', how = 'inner')

      name  id  age
0      Bob   2   20
1  Charlie   3   21

In [ ]:
cafe = pandas.read_csv("prices.csv")

In [ ]:
cafe.head()

,drink_type,price_small,price_medium,price_large,simple,double
0,frappucino,5.0,5.7,6.4,NaN,NaN
1,iced chocolate,5.0,5.7,6.4,NaN,NaN
2,iced chai latte,5.0,5.7,6.4,NaN,NaN
3,milkshake (syrup),4.6,5.3,6.0,NaN,NaN
4,milkshake (natural fruit extract),4.6,5.3,6.0,NaN,NaN

In [ ]:
cafe.loc[cafe['price_small']<5,'simple'] = 2
cafe.head()

,drink_type,price_small,price_medium,price_large,simple,double
0,frappucino,5.0,5.7,6.4,NaN,NaN
1,iced chocolate,5.0,5.7,6.4,NaN,NaN
2,iced chai latte,5.0,5.7,6.4,NaN,NaN
3,milkshake (syrup),4.6,5.3,6.0,2.0,NaN
4,milkshake (natural fruit extract),4.6,5.3,6.0,2.0,NaN

In [ ]:
cafe.loc[[0,2],'simple']= 3
cafe.head()

,drink_type,price_small,price_medium,price_large,simple,double
0,frappucino,5.0,5.7,6.4,3.0,NaN
1,iced chocolate,5.0,5.7,6.4,NaN,NaN
2,iced chai latte,5.0,5.7,6.4,3.0,NaN
3,milkshake (syrup),4.6,5.3,6.0,2.0,NaN
4,milkshake (natural fruit extract),4.6,5.3,6.0,2.0,NaN

In [ ]:
cafe["simple"]=cafe['simple'].interpolate(method = 'linear')

In [ ]:
pivot = cafe.pivot(index = 'drink_type', columns = 'simple', values = 'price_small')

In [ ]:
count =df.groupby("Year")["Name"].count().to_dict()
print(count)

{1896: 380, 1900: 1936, 1904: 1301, 1906: 1733, 1908: 3101, 1912: 4040, 1920: 4292, 1924: 5693, 1928: 5574, 1932: 3321, 1936: 7401, 1948: 7480, 1952: 9358, 1956: 6434, 1960: 9235, 1964: 9480, 1968: 10479, 1972: 11959, 1976: 10502, 1980: 8937, 1984: 11588, 1988: 14676, 1992: 16413, 1994: 3160, 1996: 13780, 1998: 3605, 2000: 13821, 2002: 4109, 2004: 13443, 2006: 4382, 2008: 13602, 2010: 4402, 2012: 12920, 2014: 4891, 2016: 13688}

In [ ]:
df2 = pandas.DataFrame({
    'day':    ['Mon', 'Mon', 'Tue', 'Tue'],
    'drink':  ['coffee', 'coffee', 'tea', 'tea'],  # Mon+coffee appears twice
    'sales':  [30, 15, 25, 10]
})

df2

   day   drink  sales
0  Mon  coffee     30
1  Mon  coffee     15
2  Tue     tea     25
3  Tue     tea     10

In [ ]:
df2.pivot_table(index='day', columns='drink', values='sales', aggfunc='sum')

drink  coffee   tea
day
Mon      45.0   NaN
Tue       NaN  35.0